#!/usr/bin/env bash

if [ ! -z "$PGID" ]; then
    groupmod -o -g $PGID www-data
    usermod -o -u $PUID -g www-data www-data
fi

if [ ! -z "$PGID" ]; then
    groupmod -o -g $PGID nginx
    usermod -o -u $PUID -g nginx nginx
fi

if [ ! -z "$COMPOSER_REPO_PACKAGIST" ]; then
    composer config -g repo.packagist composer $COMPOSER_REPO_PACKAGIST
fi

if [ -n "$APP_PATH" ] && [ -a "${APP_PATH}/composer.json" ]; then
    cd "$APP_PATH"

    if [ -n "$APP_ENV" ] && ([ "$APP_ENV" = "prod" ] || [ "$APP_ENV" = "production" ]); then
        composer install --optimize-autoloader --no-dev
    else
        composer install
    fi
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
