#!/usr/bin/env bash

if [ ! -z "$PGID" ]; then
    groupmod -o -g $PGID www-data
    usermod -o -u $PUID -g www-data www-data
fi

if [ ! -z "$PGID" ]; then
    groupmod -o -g $PGID nginx
    usermod -o -u $PUID -g nginx nginx
fi

if [ ! -z "$COMPOSER_REPO_PACKAGIST" ]; then
    composer config -g repo.packagist composer $COMPOSER_REPO_PACKAGIST
fi

is_composer_install="${COMPOSER_INSTALL:-true}"

if [ -n "$APP_CODE_PATH" ] && [ -a "${APP_CODE_PATH}/composer.json" ] && [ "$is_composer_install" = true ]; then
    cd "$APP_CODE_PATH"

    if [ -n "$APP_RUN_ENV" ] && ([ "$APP_RUN_ENV" = "prod" ] || [ "$APP_RUN_ENV" = "production" ]); then
        composer install --optimize-autoloader --no-dev
    else
        composer install
    fi
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
